import pkg from "../package.json" with { type: "json" };

/** Package version, read from `package.json` so it can never drift from the published version. */
export const VERSION: string = pkg.version;

export type {
  ApiErrorBody,
  JournalEntry,
  PublishRequest,
  RunDetail,
  RunError,
  RunEvent,
  RunEventType,
  RunOrigin,
  RunStartedResponse,
  RunStatus,
  RunSummary,
  RunWorkflowRequest,
  SubflowInfo,
  TestStepRequest,
  TestStepResponse,
  WorkflowDetail,
  WorkflowSummary,
  WorkflowVersion,
} from "./api-types";
export {
  type ConfigOf,
  type DeepExpr,
  ref,
  type StepConfig,
  type StepsBuilder,
  type TriggerConfigOf,
  tpl,
  type WorkflowBuilder,
  workflow,
} from "./builder";
export type { ClientOptions, FlowlineClient } from "./client";
export {
  type BranchSignal,
  branch,
  type CallbackHandle,
  defineNode,
  definePlugin,
  defineTrigger,
  FLOWLINE_SIGNAL,
  FlowlineDefinitionError,
  type FlowlineServices,
  invokeSubflow,
  isSignal,
  type Logger,
  type LoopSignal,
  loop,
  type NodeContext,
  type NodeDefinition,
  type NodeResult,
  type PluginDefinition,
  type PollArgs,
  type PollContext,
  type PollItem,
  type PollResult,
  type ResumeInfo,
  type RetryPolicy,
  type Signal,
  type StopSignal,
  type SubflowSignal,
  type SuspendSignal,
  stop,
  suspend,
  type TransformRuntime,
  type TriggerDedupe,
  type TriggerDefinition,
} from "./define";
export {
  type UnreachableGroup,
  unreachableSteps,
} from "./design-checks";
export { FatalError, type FatalErrorOptions, RetryableError } from "./errors";
export {
  branchesFor,
  checkFields,
  configValueAt,
  describeType,
  fieldsToJsonSchema,
  isAnySchema,
  isAssignable,
  outputSchemaFor,
  payloadSchemaFor,
  schemaAtPath,
  secretExprPath,
  subflowOutputFields,
  subflowOutputSchema,
} from "./json-schema";
export { isPrivateAddress, isPrivateHost, normalizeHost } from "./net";
export {
  collectRefs,
  FlowlineRefError,
  formatRefPath,
  isRef,
  isTpl,
  parseRefPath,
  parseTemplate,
  type RefPath,
  type RefRoot,
  type ResolveScope,
  renderTemplate,
  resolveValue,
  type TemplatePart,
} from "./refs";
export { createRegistry, type Registry } from "./registry";
export {
  availableScope,
  describeSubflowOutput,
  type ScopeEntry,
  type ValidationContext,
} from "./scope";
export {
  dropHiddenFields,
  hiddenFields,
  isFieldShown,
  showIfOf,
  showIfProblems,
} from "./show-if";
export {
  allStepIds,
  codeBlocksRename,
  duplicateStep,
  FlowlineTreeError,
  type FoundStep,
  findStep,
  generateStepId,
  insertStep,
  isGeneratedStepId,
  moveStep,
  removeStep,
  renameStepId,
  type StepLocation,
  updateStep,
  walkSteps,
} from "./tree";
export type {
  BranchSpec,
  DurationInput,
  FieldDecl,
  FieldType,
  JSONSchema,
  Literal,
  Manifest,
  NodeManifest,
  OutputSpec,
  PluginManifest,
  RefExpr,
  ResumeSpec,
  RuleOperatorMeta,
  RuleValueType,
  ShowIf,
  Step,
  TplExpr,
  TriggerConfig,
  TriggerKind,
  TriggerManifest,
  UiMeta,
  ValueExpr,
  WorkflowDoc,
} from "./types";
export { fields, secret, sensitive, UI_META_KEY, ui } from "./ui";
export { checkJson, hasErrors, type Issue, type IssueCode, validateWorkflow } from "./validate";
